version: "3"
services:
  client:
    build:
      context: ./dockerfile/
      dockerfile: Dockerfile_client
    ports:
      - "8082:82"
    # 権限の有効化
    privileged: true
    environment:
      # 定数
      TZ: Asia/Tokyo
    volumes:
      - ../:/workspaces
    command: /sbin/init ## これ
