version: "3.4"
services:
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    image: server-dev
    ports:
      - "8082:8080"
    privileged: true
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./server/:/workspaces
    working_dir: /workspaces
    command: /sbin/init
  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
    image: server-prod
    tty: true
    profiles:
        - prod
    ports:
      - "8083:8080"
    privileged: true
    environment:
      TZ: Asia/Tokyo

  db:
    image: mysql:8.0.20
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: sample01
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8081:3306"
    # 権限の有効化
    privileged: true
    volumes:
      - ./DB:/workspaces
      - ./DB/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # 権限の有効化
    privileged: true
    environment:
      # 定数
      TZ: Asia/Tokyo
    volumes:
      - ./client:/workspaces
    command: /sbin/init
