version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # 権限の有効化
    privileged: true
    environment:
      # 定数
      TZ: Asia/Tokyo
    volumes:
      - ./server/:/workspaces
    command: /sbin/init

  db:
    image: mysql:8.0.20
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: sample01
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8081:3306"
    # 権限の有効化
    privileged: true
    volumes:
      - ./DB:/workspaces
      - ./DB/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    privileged: true # 権限の有効化
    stdin_open: true # 標準入出力とエラー出力をコンテナに紐づける
    tty: true # キーボード入力をコンテナに紐づける
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./client:/usr/src
    working_dir: /usr/src/app
    command: /bin/sh -c "yarn install && yarn start" # reactの起動なども行っている。
