definitions:
  model.Book:
    properties:
      author:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
  model.User:
    properties:
      authCount:
        type: integer
      email:
        example: test@mail.com
        type: string
      id:
        type: integer
      isAdmin:
        type: boolean
      lastname:
        example: Packard
        type: string
      name:
        example: Jack
        type: string
    type: object
info:
  contact: {}
  description: 見本apiです
  license:
    name: intime
  title: gin-swagger todos
  version: "1.0"
paths:
  /books:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
      summary: bookinfoをjsonで返す
      tags:
      - Book
    post:
      consumes:
      - application/json
      description: Takes a book JSON and store in DB. Return saved JSON.
      parameters:
      - description: book data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: book情報登録
      tags:
      - Book
  /books/{id}:
    get:
      parameters:
      - description: book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: bookinfoをIDで検索しjsonで返す
      tags:
      - Book
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Userをjsonで返す
      tags:
      - User
swagger: "2.0"
