info:
  contact: {}
  description: 見本apiです
  license:
    name: intime
  title: gin-swagger todos
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: bookinfoをjsonで返す
      tags:
      - Book
swagger: "2.0"
