version: "3"
services:
  db:
    image: mysql:8.0.20
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: sample01
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "8081:3306"
    # 権限の有効化
    privileged: true
    volumes:
      - ../:/workspaces
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql

