name: Create Weekly Milestone
on:
  schedule:
  - cron: '0 0 * * Thu'

jobs:
  create-weekly-milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6.3.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const date = new Date(Date.now() + ((new Date().getTimezoneOffset() + (9 * 60)) * 60 * 1000));
            const startDate = (date.getMonth() + 1) + "/" + date.getDate()
            date.setDate(date.getDate() + 7)
            const due_on = date.toISOString()
            const endDate = (date.getMonth() + 1) + "/" + date.getDate()
            github.issues.createMilestone({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: startDate + " ～ " + endDate,
              due_on: due_on,
              description: startDate + "～" + endDate + "のマイルストーン"
            })
